#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

SV_NAME="$(basename "$(pwd)")"

log() {
    echo "[$SV_NAME] $*"
}

if [ "${DISABLE_RESTART_SESSION_DIALOG_WINDOW:-0}" == "1" ]; then
    # Disable the service.
    log "Dialog window disabled: disabling service..."
    s6-touch /var/run/s6/services/"$SV_NAME"/down
    s6-svc -xd /var/run/s6/services/"$SV_NAME"
    exit 0
fi

DIALOG_WIDTH=200

yad \
    --title="PuTTY" \
    --window-icon=/opt/novnc/images/icons/master_icon.png \
    --width=$DIALOG_WIDTH \
    --posx=$(expr $DISPLAY_WIDTH - $DIALOG_WIDTH) \
    --posy=5 \
    --fixed \
    --on-top \
    --no-escape \
    --button="Restart PuTTY session":"killall putty" \
    --buttons-layout=center

# vim: set ft=sh :
